/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PaidOrdersRouteImport } from './routes/paid-orders'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CashRegisterRouteImport } from './routes/cash-register'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidOrdersRoute = PaidOrdersRouteImport.update({
  id: '/paid-orders',
  path: '/paid-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRegisterRoute = CashRegisterRouteImport.update({
  id: '/cash-register',
  path: '/cash-register',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/cash-register': typeof CashRegisterRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/developer': typeof DeveloperRoute
  '/paid-orders': typeof PaidOrdersRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/cash-register': typeof CashRegisterRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/developer': typeof DeveloperRoute
  '/paid-orders': typeof PaidOrdersRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/cash-register': typeof CashRegisterRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/developer': typeof DeveloperRoute
  '/paid-orders': typeof PaidOrdersRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-sellers'
    | '/cash-register'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/developer'
    | '/paid-orders'
    | '/products'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-sellers'
    | '/cash-register'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/developer'
    | '/paid-orders'
    | '/products'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/best-sellers'
    | '/cash-register'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/developer'
    | '/paid-orders'
    | '/products'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestSellersRoute: typeof BestSellersRoute
  CashRegisterRoute: typeof CashRegisterRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  DeveloperRoute: typeof DeveloperRoute
  PaidOrdersRoute: typeof PaidOrdersRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-orders': {
      id: '/paid-orders'
      path: '/paid-orders'
      fullPath: '/paid-orders'
      preLoaderRoute: typeof PaidOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-register': {
      id: '/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof CashRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestSellersRoute: BestSellersRoute,
  CashRegisterRoute: CashRegisterRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  DeveloperRoute: DeveloperRoute,
  PaidOrdersRoute: PaidOrdersRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
